import type { RunDetail } from '@edi-bridge/contracts'

export type RunRemedy = 'retry' | 'reprocess' | 'awaitingResend' | 'replaced' | 'none'

export function runRemedy(
  run: Pick<RunDetail, 'status' | 'failureStage' | 'direction' | 'replacedBy'>,
): RunRemedy {
  if (run.status !== 'failed' || run.failureStage === null) {
    return 'none'
  }

  if (run.replacedBy !== null) {
    return 'replaced'
  }

  switch (run.failureStage) {
    case 'delivery': {
      return 'retry'
    }

    case 'mapping': {
      return 'reprocess'
    }

    case 'parse':
    case 'validation': {
      // Outbound EDIFACT is generated by our own Mapping, so no Trading Partner can resend it.
      return run.direction === 'inbound' ? 'awaitingResend' : 'none'
    }
  }
}
